<ul class="footer_menu">
    <li>
        <?=CHtml::link(
                Yii::t('site','bottom_menu_about_mercadopana'),
                Yii::app()->createUrl('/site/page',array(
                    'lang'=>Yii::app()->language,
                    'pagealias'=>'about'
                ))
                );?>
    </li>
    |
    <li>
        <?=CHtml::link(
                Yii::t('site','bottom_menu_centro_de_seguridad'),
                Yii::app()->createUrl('/site/page',array(
                    'lang'=>Yii::app()->language,
                    'pagealias'=>'centro-de-seguridad'
                ))
                );?>
    </li>
    |
    <li>
        <?=CHtml::link(
                Yii::t('site','bottom_menu_safety_center'),
                Yii::app()->createUrl('/site/page',array(
                    'lang'=>Yii::app()->language,
                    'pagealias'=>'safety-center'
                ))
                );?>
    </li>
    |
    <li>
        <?=CHtml::link(
                Yii::t('site','bottom_menu_mapa_del_sitio'),
                Yii::app()->createUrl('/site/page',array(
                    'lang'=>Yii::app()->language,
                    'pagealias'=>'mapa-del-sitio'
                ))
                );?>
    </li>
    |
    <li>
        <?=CHtml::link(
                Yii::t('site','bottom_investor_relations'),
                Yii::app()->createUrl('/site/page',array(
                    'lang'=>Yii::app()->language,
                    'pagealias'=>'investor-relations'
                ))
                );?>
    </li>
    |
    <li>
        <?=CHtml::link(
                Yii::t('site','bottom_menu_ver_otros_paises'),
                Yii::app()->createUrl('/site/page',array(
                    'lang'=>Yii::app()->language,
                    'pagealias'=>'ver-otros-paises'
                ))
                );?>
    </li>
</ul>